import Link from "next/link";
import { ShieldCheck, Users, Search, BriefcaseBusiness, ArrowRight, CheckCircle2 } from "lucide-react";
import { RegistrationForms } from "./registration-forms";

const services = [["Home maid","Cleaning, laundry and household organisation."],["Nanny support","Vetted childcare matched to your schedule."],["Once-off cleaning","Deep cleaning, moving or special occasions."],["Office cleaning","Flexible teams for offices and small businesses."]];
export default function Home(){return <main><header className="site-header"><div className="shell nav"><Link className="brand" href="/"><span className="brand-mark">MC</span><span>Maid Center <b>Zambia</b></span></Link><nav><Link href="/services">Services</Link><Link href="/process">Our process</Link><a href="#register">Registration</a><Link href="/dashboard">My account</Link></nav><Link className="button button-small" href="/auth">Sign in</Link></div></header>
<section className="hero"><div className="shell hero-grid"><div><span className="eyebrow">Household staffing and placement</span><h1>Find reliable household support with confidence.</h1><p>Maid Center Zambia helps families and businesses recruit verified maids, nannies and cleaners through a structured screening and placement process.</p><div className="hero-actions"><a className="button" href="#register">Request a professional <ArrowRight size={18}/></a><a className="button secondary" href="#register">Apply for work</a></div><div className="trust"><ShieldCheck/><span><strong>Managed verification</strong><small>Identity, references and work history are reviewed.</small></span></div></div><div className="hero-panel professional-panel"><span className="panel-label">Placement service</span><h2>A clear process for clients and professionals</h2><Journey icon={<Users/>} title="Register" copy="Create your secure account and submit the correct application" n="01"/><Journey icon={<Search/>} title="Verification" copy="Documents and references reviewed" n="02"/><Journey icon={<BriefcaseBusiness/>} title="Placement" copy="Shortlist, interview and follow-up" n="03"/><Link href="/process" className="panel-account-link">See our full process <ArrowRight size={16}/></Link></div></div></section>
<section id="services" className="section"><div className="shell"><Heading eyebrow="Our services" title="Support that fits real homes" copy="Start with a simple request. Our team confirms the details before sharing any candidate profile."/><div className="service-grid">{services.map(([t,c],i)=><Link className="service-card" href="/services" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p><strong style={{display:"inline-flex",alignItems:"center",gap:6,marginTop:10}}>View service <ArrowRight size={15}/></strong></Link>)}</div><div style={{display:"flex",justifyContent:"center",marginTop:30}}><Link className="button" href="/services">Explore all services <ArrowRight size={18}/></Link></div></div></section>
<section id="register" className="section register-section"><div className="shell"><Heading eyebrow="Start here" title="Choose the form that fits you" copy="Create your secure account while submitting your profile. NRC details and references are private and never shown publicly."/><RegistrationForms/></div></section>
<section className="safety"><div className="shell safety-grid"><div><ShieldCheck size={38}/><h2>Privacy and safeguarding first</h2></div><div><p><CheckCircle2/> Workers must be 18 or older.</p><p><CheckCircle2/> Documents are visible only to authorised administrators.</p><p><CheckCircle2/> Clients are reviewed before contacts are shared.</p></div></div></section>
<footer><div className="shell footer-grid"><div><div className="brand"><span className="brand-mark">MC</span><span>Maid Center <b>Zambia</b></span></div><p>Safer connections between homes and household professionals.</p></div><div><strong>Platform</strong><Link href="/services">Services</Link><Link href="/process">Our process</Link><a href="#register">Registration</a><Link href="/auth">Sign in</Link></div><div><strong>Location</strong><span>Lusaka, Zambia</span><span>Contact details coming soon</span></div></div><div className="shell copyright">© 2026 Maid Center Zambia</div></footer></main>}
function Journey({icon,title,copy,n}:{icon:React.ReactNode;title:string;copy:string;n:string}){return <div className="journey"><div>{icon}<span><strong>{title}</strong><small>{copy}</small></span></div><b>{n}</b></div>}
function Heading({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="section-heading"><span className="eyebrow dark">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div>}
